name: dospace
description: Client library to interact with the DigitalOcean Spaces API.
version: 0.13.15
homepage: https://github.com/olaar09/dartspace
author: olaar09

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  meta: ^1.3.0
  crypto: ^3.0.0
  http: ^0.13.0
  xml: ^5.0.2

dev_dependencies:
  test: ^1.0.0
  ini: ^2.1.0-beta
